# Sample configuration for AI Trading Agent with High-Frequency Trading
# This demonstrates how to set up the high-frequency trading strategy with StatelessVM

[data]
providers = ["avalanche", "coinmarketcap"]
update_interval_ms = 1000
cache_duration_s = 60
avalanche_rpc_url = "https://api.avax.network/ext/bc/C/rpc"

[llm]
provider = "openai"
api_key = "${LLM_API_KEY}"
model = "gpt-4"
temperature = 0.3
max_tokens = 1000
retry_delay_ms = 1000
retry_attempts = 3
backoff_ms = 2000

[strategies]
active_strategies = ["high-frequency"]
risk_level = 2
max_position_size = "0.5"  # 0.5 ETH maximum position
max_slippage_bps = 50      # 0.5% max slippage
min_confidence_score = 75.0

# High-Frequency trading specific configuration
[strategies.high_frequency]
enabled = true
monitored_dexes = [
    "uniswap",
    "sushiswap",
    "quickswap",
    "traderjoe"
]
# Trading pairs to monitor
[[strategies.high_frequency.trading_pairs]]
token_a = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"  # WETH
token_b = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"  # USDC
trade_amount = "0.1"  # 0.1 ETH per trade
min_profit_threshold_percent = 0.2  # 0.2% minimum profit

[[strategies.high_frequency.trading_pairs]]
token_a = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"  # WETH
token_b = "0x6B175474E89094C44Da98b954EedeAC495271d0F"  # DAI
trade_amount = "0.1"  # 0.1 ETH per trade
min_profit_threshold_percent = 0.25  # 0.25% minimum profit

min_profit_multiplier = 1.5  # Net profit must be 1.5x gas cost
max_slippage_percent = 0.5  # 0.5% maximum slippage
max_trade_size_usd = 1000.0  # Maximum $1000 per trade
min_block_confirmations = 1  # Only need 1 confirmation for speed
scan_interval_ms = 500  # Scan every 500ms
gas_boost_percent = 10  # Boost gas price by 10% above fast price
wallet_address = "${WALLET_ADDRESS}"
security_verification_enabled = true
max_risk_score = 7  # Medium risk tolerance

[execution]
relayer_url = "https://relayer.example.com"
avalanche_rpc_url = "https://api.avax.network/ext/bc/C/rpc"
stateless_vm_url = "https://stateless-vm.example.com"
max_gas_price_gwei = 200
confirmation_blocks = 1
bundle_timeout_ms = 30000
retry_attempts = 3
wallet_key = "${WALLET_KEY}"
wallet_address = "${WALLET_ADDRESS}"
max_risk_score = 5
witness_generation_timeout_ms = 5000

[security]
verification_mode = "DeploymentOnly"
verify_contracts = true
max_risk_score = 7
verify_reentrancy = true
verify_integer_underflow = true
verify_integer_overflow = true
verify_unchecked_calls = true
verify_upgradability = true
verify_mev_vulnerability = true
verify_cross_contract_reentrancy = true
verify_precision_loss = true
verify_gas_griefing = true
cache_verification_results = true
verification_cache_duration_s = 3600
